[project]
name = "gifmaker"
version = "0.1.0"
description = ""
authors = [
    {name = "Kyle Marden",email = "demolaze@Mac.home"}
]
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
    "pyside6 (>=6.11.1,<7.0.0)"
]

[tool.poetry]
packages = [{include = "gifmaker", from = "src"}]


[tool.poetry.group.dev.dependencies]
loguru = "^0.7.3"
pytest = "^9.1.1"
ruff = "^0.16.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
